### ISSUE TITLE
atmospheric effects on vessels in orbit

### ISSUE THREAD

**Issue by dafrandle** [LGhassen/Scatterer#58]
so I was launching a rocket after I got to about 115 km and my ship started to become blue-ish as if someone took a mask of the vessel in photoshop and placed a transparent solid blue layer overtop of it
![issue](https://user-images.githubusercontent.com/23199268/54409151-427ba300-46b3-11e9-98a3-4b42b9571d20.JPG)

this only happens on the daytime side of the planet, on the day/night terminator the ship will turn orange-ish
further investigation revealed that the issue starts/ends at exactly 160 km
the issue just becomes less pronounced as altitude decreases.

Although i'm running 91 mods I can't think of any other mod that could conceivably cause something like this other than Scatterer

I will troubleshoot this further in the coming week
(btw here is my data folder so you can see what mods i have)
![modlist](https://user-images.githubusercontent.com/23199268/54409561-6c35c980-46b5-11e9-90d5-c6a36126e3d7.JPG)

**Comment by dafrandle** [comment]
Ok here is the altitudes this issues is in effect at.
On my return to kerbin from the mun I made sure to test this

The issue presented itself at exactly 160 km along with a lag spike while things loaded
the issue just becomes less pronounced as altitude decreases.

**Comment by dafrandle** [comment]
it would appear that my previous investigations were not through enough (this is still the same play session)
![isues2](https://user-images.githubusercontent.com/23199268/54410984-b326bd80-46bb-11e9-8621-42bd7e57b287.JPG)

**Comment by LGhassen** [comment]
Can you test with ocean shader disabled?

**Comment by maccollo** [comment]
I get this issue aswell. Tried it on a fresh install with only KSP and scatterer, and I made sure to test with both old and new graphics drivers. The glitches turn up in the region between low orbit and 1000 km. I recorded the ones I found find:

Default scatterer settings: This shows the blue tint overlay on the vessel, and also the surface z-fighting. There are also a couple of other artefacts where the atmosphere gets and yellow band and blinks
https://youtu.be/GEUdt-R9M58

In this video you see the same effect, but also a blue sphere appearing on top of Kerbin. Around 35 second a kind of transition is also visible where the atmosphere disappears for just one or two frames.
https://youtu.be/XOQEbATLxJs

Also, here is a pass with the Ocean shader turned off. The surface goes crazy with z-fighting.
https://youtu.be/9hIgdVPACPg

**Comment by LGhassen** [comment]
Thanks for the detailed report.

**Comment by LGhassen** [comment]
@maccollo @dafrandle please test with the newest version, it should fix it.

**Comment by maccollo** [comment]
> @maccollo @dafrandle please test with the newest version, it should fix it.

That was quick! The spacecraft tint seems to be fixed, and also those strange atmospheric effects. The ground z-fighting is still there, though it's less noticeable. There are still those little z-fighting spots but it seems there are fewer of them when Ocean shader is enabled. 

With ocean shader off the z-fighting is still very obvious, although the effect is reduced if you look at an angle, and it seems to depend more on where the center of the camera is looking, because if I look at the horizon with a high view angle the z-fighting doesn't trigger on the part of the screen that's looking straight down at the planet. There are also big blocks of black squares that turn up at certain angles
https://youtu.be/G1xPUcqUpVM

**Comment by LGhassen** [comment]
Thanks for the update, I will keep working on this. In the meantime, if you run your game in Directx11 it should get rid of the artifacts.

**Comment by iGGnite** [comment]
Hello, the bug is back. I'm playing with minimal mods https://youtu.be/rv_Ac79FazQ

**Comment by LGhassen** [comment]
@iGGnite  can you make a full report? With versions and details?

**Comment by iGGnite** [comment]
https://www.dropbox.com/sh/2a0mhwi5x2w2sz5/AADE7ZBSI9RPQHkU9Z4DLfeAa?dl=0
Version 1.8.1, ill also drop this in the atmospheric edge problem https://github.com/LGhassen/Scatterer/issues/66

**Comment by LGhassen** [comment]
@iGGnite this bug is still happening?

**Comment by iGGnite** [comment]
No, I uninstalled planetshine on 1.8.1 and I dont envounter this any more.
version 1.9, Idk

**Comment by LGhassen** [comment]
Thanks, I'm closing this

**Comment by JaneWalor** [comment]
Hello. I know that this thread is closed, but the solution provided by iGGnite probaly just worked for him. I have this issue from version 1.8.1 to 1.9.1, and I tried to find a fix for it, or even mess with scatterer's code and nothing worked. I tried also without any mods except Scatterer (version 0.0722), Sigma Dimensions and Rescale Continued on version 1.9.1. I used configs x7.6 and x10. On version 1.8.1 I tred only x10.625 and x10. I will provide Ksp.log as soon as posible with only these mods instaled. Any help would be apreciated.

**Comment by LGhassen** [comment]
@JaneWalor does this happen on the night side? If not it maybe just that the atmosphere becomes too high with rescale, so try setting scatterer 's experimentalAtmo scale down to 1.0 or 0.5 and report back

**Comment by JaneWalor** [comment]
As on rescale x7.6 It hapens only on the day side. It starts about at 50 km to 130 km above ONLY Kerbin surface. The night side, cannot realy tell I curently cannot send Ksp.log because I am not at my house, but when I will be able to (for sure today) I will send it. And experimentalAtmo scale, I will also try it. Thanks.

**Comment by JaneWalor** [comment]
So I am back home, and it works! Its incredible! I have been having this bug for a month and its finaly fixed! I changed experimentalAtmo scale to 1.0 and now everything looks incredible! I don't know how to thank you. So good luck keeping scatterer up, the latest version is amazing! And also, Merry Christmas!

**Comment by JaneWalor** [comment]
here are the results
![screenshot0](https://user-images.githubusercontent.com/76256308/102769267-b49e1300-4382-11eb-83f3-302ab422090c.png)

**Comment by JaneWalor** [comment]
Thanks again!

**Comment by LGhassen** [comment]
I should probably add a PSA for rescale or something. Thanks for confirming and merry christmas!

**Comment by JaneWalor** [comment]
Finaly i can crash my rockets and not worry about the visuals being broken. :D

**Comment by llamana** [comment]
Hey guys

I'm having the same problem with the blue tint in ships around kerbin orbit.
Trying to find the experimentalAtmo scale but no luck. I've been looking in the in-game config as well as the game scatterer data folder config file and I'm stumped. Any help would be appreciated

**Comment by Abstractsolitude** [comment]
Hi guys,
I'm also having exactly the same issue as Ilamana. Like them, I've also tried to find the 'experimentalAtmo scale', but with no luck.
is that a setting that's been removed since JaneWalor posted it as a fix?
Anyway, any advice or help would be awesome.
Thanks
![Scatterer bug](https://user-images.githubusercontent.com/94222262/141614991-539b185e-4596-419d-8567-afb4f1613327.png)

**Comment by LGhassen** [comment]
ExperimentalAtmoScale has been removed in the newest version. This bug seems ti be back so it's reopened.

**Comment by nokfox** [comment]
Hi!  
Are there any ways to solve this problem, or just wait for now?  KSP 1.12, scatterer 0.0825

**Comment by LGhassen** [comment]
@nokfox @Abstractsolitude try this fix https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip112x-scatterer-atmospheric-scattering-00825-11112021-scattering-improvements-in-game-atmo-generation-and-multi-sun-support/&do=findComment&comment=4061711

**Comment by llamana** [comment]
> @nokfox @Abstractsolitude try this fix https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip112x-scatterer-atmospheric-scattering-00825-11112021-scattering-improvements-in-game-atmo-generation-and-multi-sun-support/&do=findComment&comment=4061711

This fix worked for me! Thank you!

**Comment by Abstractsolitude** [comment]
This worked!! Thank you so much :)

**Comment by LGhassen** [comment]
Fixed in 0.0827
